# UI User Interface 
define audio.MenuButtonBlick = "audio/ui/ButtonClick.flac"
define audio.MenuButtonStartHover = "audio/ui/ButtonHover_MainMenu.flac"
define audio.CloseMenu = "audio/ui/Close_Menu.flac"
define audio.Load = "audio/ui/Load.flac"
define audio.Save = "audio/ui/Save.flac"

# Music
define audio.EndThemeBad = "audio/music/BadEnd.flac"
define audio.EndThemeGood = "audio/music/GoodEnd.flac"
define audio.EndThemeNeutral = "audio/music/NeutralEnd.flac"
define audio.RoomThemeBedroom = "audio/music/Room#1.flac"
define audio.RoomThemeLivingRoom = "audio/music/Room#2.flac"
define audio.RoomThemeKitchen = "audio/music/Room#3.flac"
define audio.RoomThemeAttic = "audio/music/Room#4.flac"
define audio.MenuTheme = "audio/music/TitleTheme.flac"

# Sound effects
define audio.MaliceIncrease = "audio/gameplay/Malice Point Finale.wav"
define audio.BoxOpeningTheme = "audio/gameplay/Fur_Elise_Opening.wav"
define audio.ScreenPanning = "audio/gameplay/Directional_Button.flac"
define audio.InteractableHover = "audio/gameplay/Item Hover Finale.wav"
define audio.HorribleBadEnding = "audio/gameplay/Bad_End.flac"
define audio.AtticFootsteps = "audio/gameplay/Attic_Footsteps.wav"
define audio.BedroomHorror = "audio/gameplay/Bedroom_Horror.mp3"
define audio.AtticRealization = "audio/gameplay/Attic_Realization.mp3"
define audio.DoorOpen = "audio/gameplay/Nicole_Door.wav"
define audio.DoorCreak = "audio/gameplay/Emi_Door.mp3"
define audio.Diary = "audio/gameplay/Nicole_Diary.wav"
define audio.Paper = "audio/gameplay/Doll_Paper.wav"
define audio.Break = "audio/gameplay/Doll_Break.wav"
define audio.Draw = "audio/gameplay/Emi_Draws.mp3"
define audio.Spill = "audio/gameplay/Doll_Glass.wav"
define audio.Scratch = "audio/gameplay/Doll_Scratch.wav"
define audio.Hungry = "audio/gameplay/Stomach_Growl.wav"
define audio.SetTable = "audio/gameplay/Setting_Table.wav"
define audio.Dinner = "audio/gameplay/Dinner_Scene.wav"
define audio.Click = "audio/gameplay/Reveal_End.wav"
define audio.Hum = "audio/gameplay/Reveal_Hum.wav"
define audio.Redact = "audio/gameplay/Redacted_Hum.wav"
define audio.Night = "audio/gameplay/Night_Relax.mp3"
