# ui audio
define audio.BadEndingMusic = "audio/ui/BadEnd.flac"
define audio.MenuButtonBlick = "audio/ui/ButtonClick.flac"
define audio.MenuButtonStartHover = "audio/ui/ButtonHover_MainMenu.flac"
define audio.CloseMenu = "audio/ui/Close_Menu.flac"
define audio.Load = "audio/ui/Load.flac"
define audio.Save = "audio/ui/Save.flac"

define audio.ScreenPanning = "audio/gameplay/Directional_Button.flac"
define audio.InteractableHover = "audio/gameplay/Hover_Interactable_Item.flac"
define audio.ObtainedItem = "audio/gameplay/Item_Obtained.flac"
define audio.ItemUnusable = "audio/gameplay/Item_Unusable.flac"
define audio.SuspicionMeterChange = "audio/gameplay/Suspicion_Meter.flac"
define audio.Footsteps = "audio/gameplay/Transfer.flac"
define audio.HorribleBadEnding = "audio/gameplay/BadEnd.flac"
