# ui audio
define audio.BadEndingMusic = "audio/ui/BadEnd.flac"
define audio.MenuButtonBlick = "audio/ui/ButtonClick.flac"
define audio.MenuButtonStartHover = "audio/ui/ButtonHover_MainMenu.flac"
define audio.CloseMenu = "audio/ui/Close_Menu.flac"
define audio.Load = "audio/ui/Load.flac"
define audio.Save = "audio/ui/Save.flac"

define audio.BoxOpeningTheme = "audio/gameplay/Fur_Elise_Opening.wav"
define audio.ScreenPanning = "audio/gameplay/Directional_Button.flac"
define audio.InteractableHover = "audio/gameplay/Item Hover Finale.wav"
define audio.ObtainedItem = "audio/gameplay/Item_Obtained.flac"
define audio.ItemUnusable = "audio/gameplay/Item_Unusable.flac"
define audio.MaliceIncrease = "audio/gameplay/Malice Point Finale.wav"
define audio.Footsteps = "audio/gameplay/Room Cleared Finale.flac"
define audio.HorribleBadEnding = "audio/gameplay/Bad_End.flac"
define audio.AtticFootsteps = "audio/gameplay/Attic_Footsteps.wav"
define audio.BedroomHorror = "audio/gameplay/Bedroom_Horror.mp3"
define audio.AtticRealization = "audio/gameplay/Attic_Realization.mp3"
define audio.DoorOpen = "audio/gameplay/Nicole_Door.wav"
define audio.DoorCreak = "audio/gameplay/Emi_Door.mp3"
define audio.Diary = "audio/gameplay/Nicole_Diary.wav"
define audio.Paper = "audio/gameplay/Doll_Paper.wav"
define audio.Break = "audio/gameplay/Doll_Break.wav"
